name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  path_provider: ^2.0.14
  sqlite3_flutter_libs: ^0.5.13
  prompt_dialog: ^1.0.9
  nostr:
    git:
      url: https://github.com/no-prob/dart-nostr.git
      ref: message-types
      resolved-ref: "4e4de5bbe420d338b23f43b85084c0610020100c"
  drift: ^2.7.0
  badges: ^3.1.1
  intl: ^0.18.1
  timezone: ^0.9.2
  flutter_contacts: ^1.1.6
  rxdart: ^0.27.7


dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.7.0
  flutter_lints: ^2.0.1
  test: ^1.24.2

flutter:
  uses-material-design: true
