on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: Build & Release
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1.5.0
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.10.1
      - run: flutter pub get
      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: dart analyze
      # Not sure when -o web:build/web is there, if it will still be buildable
      # for the other targets, linux and apk
      # - run: dart run build_runner build
      - run: dart run build_runner build --delete-conflicting-outputs -o web:build/web/
      - run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      - name: Display structure of build files
        run: ls -R
        working-directory: ./web
      - name: Deploy to GitHub Pages
        run: |
          cd build/web
          git init
          git status
          # https://github.com/ntheden/messages.git then the following:
          # git remote add origin https://${{secrets.GH_DEPLOY}}@github.com/ntheden/messages.git
          # git checkout -b gh-pages
          git remote add origin https://github.com/ntheden/message.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/debug/*
          tag: v0.0.${{ github.run_number }}
      - run: flutter build linux
        with:
          artifacts: build/linux/x64/debug/bundle/*
          tag: v0.0.${{ github.run_number }}
